version: "3.8"

services:
  mongo:
    image: mongo:6
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: green-backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      # Override MONGO_URI if needed
      MONGO_URI: mongodb+srv://pavansivasankar117_db_user:QjwdN4aXhLeSa62P@cluster0.0ozp3kd.mongodb.net/chatify_db?retryWrites=true&w=majority&appName=Cluster0

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: greeen-frontend
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  mongo_data:
